### ISSUE TITLE
Some Youtube videos don't play and give no error as to why

### ISSUE THREAD

**Issue by warhorseman** [TannerGabriel/discord-bot#100]
**Describe the bug**
When using /play to play certain songs from YouTube, the bot will join and then as soon as the video file or clip is played the bot leaves and does not give an error as to why. 

**To Reproduce**
1. /play https://www.youtube.com/watch?v=_hvra3gh1nQ

**Expected behavior**
I expect the bot to join a discord channel, find the song that was linked or searched for, start to play said song and then as soon as the song is about to start the bot leaves the channel and says queue finished without playing the song.

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS:  Ubuntu 20.04.3 LTS
 - CPU architecture:  x64

**Dependency versions:**
 - Nodejs version: 16.9.1
 - npm --version 7.21.1
 - music-bot@1.0.0 /home/Jbot/discord-bot
├── @discordjs/opus@0.6.0
├── discord-player@5.0.2
├── discord.js@13.1.0
├── ffmpeg@0.0.4
├── fluent-ffmpeg@2.1.2
└── ytdl-core@4.9.1

**Additional context (optional)**

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/TannerGabriel/discord-bot/issues?q=is%3Aissue)

**Comment by TannerGabriel** [comment]
@warhorseman I suspect that this is because of some copyright issue with the song or something related to that, but I am not certain at the current time. That said, I will take a closer look when I find the time to do so.
