### ISSUE TITLE
Bot does not respond to my commands, only goes online with no issues in console

### ISSUE THREAD

**Issue by dyaricoderman** [TannerGabriel/discord-bot#101]
I start up the bot with no issues. I then get "Ready!" in console and I try "!deploy".
No response.
No errors in console.
I even try the normal play commands, but still no response. Please help!
![image](https://user-images.githubusercontent.com/65177436/133665987-f083ea0b-e047-4814-9a8b-f8543bf59f5d.png)
![image](https://user-images.githubusercontent.com/65177436/133665998-64dd8c31-b14c-49ff-abff-863d6f2efed0.png)

**Comment by dyaricoderman** [comment]
fixed issue, was using outdated node version

**Comment by Mahakam20000** [comment]
Same problem with the docker version
