### ISSUE TITLE
Error emitted from the queue: Status code: 410 ["Cannot play a resource that has already ended."]

### ISSUE THREAD

**Issue by TheBudderBomb** [TannerGabriel/discord-bot#104]
**Describe the bug**
Sometimes when playing a song, it will queue up but not start, the bot then crashes with the error: Cannot play a resource that has already ended

**To Reproduce**

Dont judge me, but it specifically has errored like this on two songs ive tried and always error like this on these songs: https://www.youtube.com/watch?v=Wc5IbN4xw70 & https://www.youtube.com/watch?v=j0lN0w5HVT8
1. launch bot
2. use command /play <any of the two videos name>
3. observe queue fail and crash bot

**Expected behavior**
The expected behavior is for the songs to queue up and then play in the voice channel rather than crash
![sc_1](https://user-images.githubusercontent.com/26120918/133854323-0366f4c0-13db-4e24-9252-d36c3635ab59.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CPU architecture: PROCESSOR_ARCHITECTURE=AMD64

**Dependency versions:**
 - Nodejs version: node v16.9.1
 - YTDL-core version: ^4.9.1
 - Other dependencies: {
    "@discordjs/opus": "^0.6.0",
    "@discordjs/voice": "^0.6.0",
    "discord-player": "^5.0.2",
    "discord.js": "^13.1.0",
    "ffmpeg": "0.0.4",
    "ffmpeg-static": "^4.4.0",
    "fluent-ffmpeg": "^2.1.2",
    "node-gyp": "^8.2.0",
    "node-opus": "^0.3.3",
    "opusscript": "^0.0.8",
    "python": "^0.0.4",
    "ytdl-core": "^4.9.1"
  }

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/TannerGabriel/discord-bot/issues?q=is%3Aissue)

**Comment by escornbar** [comment]
update discord-player
put this on your console, npm i discord-player@latest

**Comment by escornbar** [comment]
I've encountered the same problem with you.
Resolved it by updating the discord-player version.
Put this on your console/terminal, npm i discord-player@latest

**Comment by TheBudderBomb** [comment]
Alrighty, thats definitely done _something_, because now the only error message i get is this:
`
[Waifu] Error emitted from the queue: Status code: 410
[Waifu] Error emitted from the connection: [PlayerError] Cannot play a resource that has already ended.
`
Upon further testing, this actually happens exclusively on youtube videos that have been age restricted. Is there some way to get that restriction removed?

**Comment by TheBudderBomb** [comment]
Even further, it will attempt to queue up these "songs that are already ended" (age restricted songs) and fail/crash if you try to play them by way of keyword, i.e. : `/play Grenouer alone in the dark`. However, if you try to play them via their link, like `/play https://www.youtube.com/watch?v=EX_8ZjT2sO4`, the bot doesnt crash and instead returns a "No results were found!" in the discord channel.

**Comment by codynhanpham** [comment]
Currently using discord-player v5.1.0 and I'm facing this same problem .-.
