### ISSUE TITLE
The bot leaves VC even if the song hasn't finished playing

### ISSUE THREAD

**Issue by QWERTY-exe** [TannerGabriel/discord-bot#107]
**The bot finishes the song even if the song hasn't finished playing**
When playing a song over 15 minutes, the bot skips the song at approximately 15 minutes.

<img width="482" alt="Screen Shot 2021-09-18 at 5 09 55 pm" src="https://user-images.githubusercontent.com/69878289/133883341-45c71a9c-adf0-4efe-80f8-a10431246325.png">

**To Reproduce**
Steps to reproduce the behaviour:
1. Use the /play command.
2. Play for approximately 15 minutes, 20 for safe measure.

**Expected behaviour**
The song should play from start to finish

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur
 - CPU architecture: x64

**Dependency versions:**
 - Nodejs version: ver.16.9.1
 - YTDL-core version:  N/A

**Comment by TannerGabriel** [comment]
I have also experienced this issue, but it seems to be a problem with the `discord-player` library, which I will have to further debug in the future.

**Comment by QWERTY-exe** [comment]
If I recall correctly, the `discord-player` library is not directly managed by you? In which case, would it be a patch file intended to replace where the fault appears to be, or some contribution otherwise to fix the problem?

**Comment by TannerGabriel** [comment]
@QWERTY-exe You are correct that the `discord-player` library is not directly managed by me. I think that a direct contribution to the library would make more sense since this should be fixed for all applications using the library.

**Comment by samdammers** [comment]
I haven't had this be an issue since https://github.com/TannerGabriel/discord-bot/issues/122 discord-player configuration changes. Anecdotal evidence only, just noting.

**Comment by TannerGabriel** [comment]
@samdammers Thank you for the feedback. I will close the issue now. If anyone experiences this issue again, feel free to let me know and I will reopen it.
