### ISSUE TITLE
Change Prefix

### ISSUE THREAD

**Issue by willm132** [TannerGabriel/discord-bot#109]
Is there a way I can change the prefix from / to something else?

**Comment by TannerGabriel** [comment]
Slash commands are a special discord functionality and I don't think it is possible to change the prefix. That said, I might bring back the functionality to execute commands with a typical prefix, but I still have to find a way to do so without duplicating a lot of the code. 

## Related issue
#88

**Comment by HackMEAny** [comment]
Checkout this #92
