### ISSUE TITLE
Syntax Error node index.js

### ISSUE THREAD

**Issue by smclean117** [TannerGabriel/discord-bot#112]
**Describe the bug**
When attemping to run node index.js, getting syntax error
"/discord-bot$ node index.js
/home/ubuntu/discord-bot/index.js:63
  if (!client.application?.owner) await client.application?.fetch();
                                   ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)"

**To Reproduce**
1. clone repository
2. install npm
3. run node index.js

**Expected behavior**
bot initialises as expected

**Desktop (please complete the following information):**
 - OS: ubuntu-focal-20.04-amd64-server-20210430
 - CPU architecture: unknown, AWS server

**Dependency versions:**
 - Unknown
 - unknown

**Additional context (optional)**
attempting to run commands on AWS micro

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report

**Comment by Ao1Pointblank** [comment]
solution:
update node to v16.9.1 (required by discord.js v13 and higher)

see my issue here for more info:
https://github.com/TannerGabriel/discord-bot/issues/82

i also suggest running this in the bot's directory:
npm install opusscript node-opus

**Comment by smclean117** [comment]
Thanks, took me a while to figure out how to update nvm/node but got there in the end, all good now!

**Comment by smclean117** [comment]
> solution:
> update node to v16.9.1 (required by discord.js v13 and higher)
> 
> see my issue here for more info:
> #82
> 
> i also suggest running this in the bot's directory:
> npm install opusscript node-opus

Thanks, took me a while to figure out how to update nvm/node but got there in the end, all good now!
