### ISSUE TITLE
Bot crashes when playlists are stopped prematurely

### ISSUE THREAD

**Issue by Cephalozyg** [TannerGabriel/discord-bot#114]
**Describe the bug**
When there are multiple songs in queue (i.e. when starting a youtube/spotify a playlist) and the bot is stopped, the bot will crash.

**To Reproduce**
1. Add multiple songs to playlist
2. Use /stop or have all users leave the voice channel
3. Bot will crash and give error below

**Expected behavior**
The bot should go back to standby on stop

**Screenshots (optional)**
![botcrash](https://user-images.githubusercontent.com/51060799/133949545-ee41e492-53a2-4b02-890d-b2fe42b730eb.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CPU architecture: x86

**Dependency versions:**
 - Nodejs version: 16.9.1
 - YTDL-core version: 4.9.1

**Additional context (optional)**
Probably like many other people, I'm jumping into this will very little programming experience since youtube is shutting down all the bots. Maybe it's just something weird about my setup, but I couldn't figure it out. 

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/TannerGabriel/discord-bot/issues?q=is%3Aissue)

**Comment by TannerGabriel** [comment]
@Cephalozyg I just tried to reproduce this issue with a playlist of over 100 songs which I stopped while the second song was playing but I didn't run into any problem. From the error message it seems like the bot needed too long to get back into the ready state, which could have multiple reasons like not having enough compute resources.

**Comment by Cephalozyg** [comment]
@TannerGabriel thank you for looking, i guess its on my end then. I'll have to dig into it some more.

**Comment by TannerGabriel** [comment]
@Cephalozyg No problem. Feel free to contact me if you need any more help.

**Comment by Cephalozyg** [comment]
I did a clean install and everything worked fine, i guess something was just corrupted/missing.
