### ISSUE TITLE
Add client activity to show commands

### ISSUE THREAD

**Issue by godsyn** [TannerGabriel/discord-bot#121]
In index.js append:
```
client.on("ready", function() {
  client.user.setActivity(`/help`, { type: 'LISTENING' });
});
```
![image](https://user-images.githubusercontent.com/508678/134132645-68bdcb74-1544-4a26-9f58-da5021432fd6.png)

**Comment by TannerGabriel** [comment]
Yes, that seems to be useful and definitely makes sense adding. Do you want to add the functionality yourself or would you prefer if I added it instead?

**Comment by godsyn** [comment]
Go for it. I've not forked, yet. Doing so now.

**Comment by youwereout** [comment]
Wanted the same functionality. Figured I would pass along the changes for the community.

**Comment by TannerGabriel** [comment]
The feature is now implemented thanks to @youwereout. We can still add improvements like changing the status when a song is played or action is executed if we want, but I'm still going to close the issue.
