### ISSUE TITLE
Bot not responding to !play

### ISSUE THREAD

**Issue by Mrxl-Games** [TannerGabriel/discord-bot#129]
The bot was meant to play the song. Sometimes it connects to the vc, other times not. It wont play the music, at all. Tried with youtube links and keywords.

**Comment by Mrxl-Games** [comment]
Fixed, nevermind

**Comment by Mrxl-Games** [comment]
Needed to make a dockerfile. Problem was based on how I used a modified version of the code

**Comment by TannerGabriel** [comment]
Ok glad you fixed it.
