### ISSUE TITLE
!play, !volumen, and search improvements for the bot 

### ISSUE THREAD

**Issue by FDSoftware** [TannerGabriel/discord-bot#13]
[100% Google Translate]:
Hi Tanner, a while ago I had made a fork of your bot and I started to improve it to use in the mini-community in which I am in discord, I went modifying the module of! Play, now you can play playlists and search for music, for that I make use of an additional module, "simple-youtube-api", although reviewing ytdl documentation well, I think it can be implemented with this one to not require the other one,
I also added a simple module to manage the volume, you can check everything from these links, I do not do PR because it has several changes that can break your original repo, and thanks for everything!
Here is a small demo of the commands:
[link to : !play module ](https://github.com/Frontend-Cafe/DJ-Pepe/blob/master/commands/volumen.js)

![image](https://user-images.githubusercontent.com/15681280/75616883-af42b400-5b35-11ea-8bdd-76d977f1cdd3.png)

[link to : !volumen module ](https://github.com/Frontend-Cafe/DJ-Pepe/blob/master/commands/volumen.js)

![image](https://user-images.githubusercontent.com/15681280/75616889-cd101900-5b35-11ea-9b6c-aa5a484c1ccf.png)

**Comment by TannerGabriel** [comment]
Your updates look great, but I don't think that I will add any extra functionality to the bot right now because it should be a simple example. Additional packages would just add unnecessary complication.

It is also great to hear that my code help you and that you enjoyed extending it.

All the best,
Gabriel Tanner
