### ISSUE TITLE
Tutorial or guide in hosting the bot

### ISSUE THREAD

**Issue by JamesRobert72** [TannerGabriel/discord-bot#130]
Hi! I am a newbie here and I quite like this discord bot. It runs well on my machine but I realize that once I turn my cmd off the bot stops working, then I came to realize that I need to host the bot. Would you mind giving me instructions or a guide on how to host the bot on Heroku or replit? Thanks! And if there are better options on how to host the bot would you mind telling me? Great!

**Comment by smoochey** [comment]
you can use heroku to host your bot. this vid shows u how, works for me like a charm https://www.youtube.com/watch?v=8qIsRzV0Hpg

**Comment by TannerGabriel** [comment]
@JamesRobert72 Yes, a tutorial might be a good idea. I was also thinking about a single deploy button for Heroku and Replit, but I still have to research if that would be possible. I will take a closer look when I find the time.

**Comment by TannerGabriel** [comment]
@JamesRobert72 @smoochey I have found the time to implement a Heroku deploy button and wanted to ask if you could try it out. If so, the code can be found on [this branch](https://github.com/TannerGabriel/discord-bot/tree/feature/heroku-deploy-button).

**Comment by smoochey** [comment]
@TannerGabriel I tried the new feature. Unfortunately, there is an error while creating the app on Heroku. "No app.json located in the repo URL provided". Maybe it's the link since the master (https://github.com/TannerGabriel/discord-bot) has no app.json and the branch does.

**Comment by Arrong18** [comment]
A good way to host your app is to use a cloud service like AWS, I am currently using a t2 micro ec2 or something and it costs about 30 pounds a year if you do the plan, split between a few of you that use a server that becomes pennies. You can even get about half a years worth of uptime for free with them too so you can always try it out. You could implement a pipeline that auto deploys it to a running ec2 as long as the user enters the details in a config file.
