### ISSUE TITLE
"FFMPEG not found"

### ISSUE THREAD

**Issue by wntrsixteen** [TannerGabriel/discord-bot#133]
I'm having trouble getting the bot to play the songs that are being queued. Even after installing FFMPEG to my computer it's continuously saying that FFMPEG is not found! 

I didn't want to write an Issue on this because this is probably a common error but I couldn't find access to the common errors list.

<img width="552" alt="Screen Shot 2021-09-29 at 9 33 30 PM" src="https://user-images.githubusercontent.com/84296589/135371137-d0b17cb3-1cc4-4ddf-ac93-6d8ea035c7dc.png">
or lists.

**Comment by dylanb-101** [comment]
I had the same error just run npm i ffmpeg-static this fixed it for me!

**Comment by wntrsixteen** [comment]
Do I run that in discord-bot folder or just in my terminal?

**Comment by TannerGabriel** [comment]
You need to install it in the discord bot folder.
