### ISSUE TITLE
Music stops after playing for a while

### ISSUE THREAD

**Issue by yaphuiyi** [TannerGabriel/discord-bot#136]
**Describe the bug**
Music stops after playing for a while or not playing at all. No error is mentioned in the console. 
![image](https://user-images.githubusercontent.com/62334893/137841339-f4d2abe0-71be-43dd-a3a5-93014cdd3204.png)

**Dependency versions:**
"dependencies": {
    "@discordjs/opus": "^0.6.0",
    "discord-player": "^5.1.0",
    "discord.js": "^13.1.0",
    "ffmpeg": "0.0.4",
    "fluent-ffmpeg": "^2.1.2",
    "ytdl-core": "^4.9.1"
  },

**Comment by rorobig** [comment]
the solution can be found here @yaphuiyi 
https://github.com/TannerGabriel/discord-bot/pull/138/commits/cc0a88bc999ba33820f352e9930771cce6cfbaaf

**Comment by TannerGabriel** [comment]
This should be fixed as described by @rorobig in one of the [latest commits](https://github.com/TannerGabriel/discord-bot/commit/cc0a88bc999ba33820f352e9930771cce6cfbaaf).
