### ISSUE TITLE
Add option in config to allow commands to be deployed by other users

### ISSUE THREAD

**Issue by Paperback** [TannerGabriel/discord-bot#146]
**Is your feature request related to a problem? Please describe.**

At the moment the bot owner must be the one to deploy the bot commands. I want to allow friends to install the bot and use it on their own without requiring me to be in their guilds or deploying the bot for them.

**Describe the solution you'd like**

Add an option to `config.json` that changes the required conditions for deploying commands here:

https://github.com/TannerGabriel/discord-bot/blob/58f649b0b918a031ca3d4c07dfad854f76ddc861/index.js#L69

This could keep the current behaviour as the default option while also allowing the option of removing the deploy requirements for those that want to use the bot like I do.

**Describe alternatives you've considered**

I'm honestly not sure why the application owner is required to deploy commands, but I assume it's there for a sane reason.

Perhaps just allowing any guild owner rather than application owner to deploy commands is more sensible? Maybe commands could be deployed automatically?

I believe @TannerGabriel also stated they might rewrite or change slash commands for prefix commands previously — so if this is all moot, no worries. 

**Additional context**

I'm happy to submit a pull request for this as it's easy to do but would like some feedback on whether it's going to be relevant in the future and any considerations for the design.

Cheers

**Comment by TannerGabriel** [comment]
@Paperback This is a good idea, but I'm not entirely sure if you need some special permissions to deploy the command (I have never tried it out). If you find the time to try it out and submit a PR, I would be happy to take a look at it.

Also, currently I have no plans on rewriting slash commands since they are the new standard on discord.
