### ISSUE TITLE
Bot not leaving VC when nobody in it

### ISSUE THREAD

**Issue by nawka12** [TannerGabriel/discord-bot#147]
**Describe the bug**
The auto-leave is not working anymore

**To Reproduce**
1.  Playing a song with the bot
2.  Leave the bot alone in the voice chat

**Expected behavior**
The bot sending `❌ | Nobody is in the voice channel, leaving...` and leave the voice chat

**Screenshots (optional)**
(Moonaroh is the bot name)
![image](https://user-images.githubusercontent.com/54880732/144772192-974b5579-cc7b-4231-8ca9-26e73e2cd653.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - CPU Architecture: x86_64

**Dependency versions:**
NodeJS v10.19.0
![image](https://user-images.githubusercontent.com/54880732/144772354-08095b68-3c7d-4ac1-a80f-8eee61d566b9.png)

**Additional context (optional)**
It worked before I update the bot to the latest version. 

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/TannerGabriel/discord-bot/issues?q=is%3Aissue)

**Comment by TannerGabriel** [comment]
@nawka12 Thank you for reporting this. I will take a closer look later this week.

**Comment by TannerGabriel** [comment]
We probably just need to set the [leaveOnEmpty](https://github.com/Androz2091/discord-player/blob/63bfb17e4bc1f846a317a49a32521b2de05cfe39/src/Player.ts#L87).
