### ISSUE TITLE
What does ban.js do?

### ISSUE THREAD

**Issue by yun00001** [TannerGabriel/discord-bot#157]
Same as the title, what does the ban.js do? ban user out to server or just ban user to not use the bot? 

If it is ban user out of the server, how can i remove it? or Disable.

Tysm.

**Comment by TannerGabriel** [comment]
`ban.js` is used to ban people from the discord server. If you want to remove it, you can just delete the file and start the bot after that.

**Comment by yun00001** [comment]
> `ban.js` is used to ban people from the discord server. If you want to remove it, you can just delete the file and start the bot after that.

Ty for the answer! and the fast reply <3
