### ISSUE TITLE
custom bot interactions?

### ISSUE THREAD

**Issue by nukinuka** [TannerGabriel/discord-bot#162]
Hello, love the bot, it is working perfectly
How to change the bot's interaction messages like these after typing the commands?
![image](https://user-images.githubusercontent.com/100720311/156229955-3982146f-7ddd-448d-8004-db9fa2db04d2.png)

I would like the bot to say something different back,
I have changed the text in index.js, but it does nothing, thank you in advance!
changed example:
![image](https://user-images.githubusercontent.com/100720311/156230234-9b2fe41c-f487-4e3e-9905-08bf767d10bc.png)

**Comment by TannerGabriel** [comment]
@nukinuka I Just tried it out and it works fine for me. Are you sure that you saved the file and restarted the bot correctly?

**Comment by nukinuka** [comment]
> @nukinuka I Just tried it out and it works fine for me. Are you sure that you saved the file and restarted the bot correctly?

Hello, thank you for your reply, I will try it again right now and get back to you

**Comment by nukinuka** [comment]
@TannerGabriel It seems to me that in index.js, the custom messages covered are only about tracks and connections, where can I find and change the rest of other messages dedicated for the queue, shuffle etc.? 
Could it be in "commands" folder or "Interface.js" under folder "discord.js/src/structures/" ?

**Comment by TannerGabriel** [comment]
The command interaction messages (e.g. `shuffle`, `swap`, etc.) can be changed in the respective files inside of the `commands` folder.
