### ISSUE TITLE
the f code not deploy

### ISSUE THREAD

**Issue by mkkoro12607** [TannerGabriel/discord-bot#163]
![image](https://user-images.githubusercontent.com/79981119/157916186-0c42475c-3642-4b2c-aeca-4e7e8a6e547c.png)
![image](https://user-images.githubusercontent.com/79981119/157916192-373d8068-016e-4df6-ad08-e6bd7982e247.png)
![image](https://user-images.githubusercontent.com/79981119/157916202-fb81f688-20e2-4c42-8f88-91530ec8ae83.png)

**Comment by TannerGabriel** [comment]
Are you getting any logs in the console? If not I would check if the deploy command is called when typing `!deploy` into Discord. If it is not called, I recommend adding the `message.read` permission and trying it again.

**Comment by mkkoro12607** [comment]
![image](https://user-images.githubusercontent.com/79981119/160619563-350f3477-2555-4af3-917d-3533363f3f43.png)
![image](https://user-images.githubusercontent.com/79981119/160619574-bc9b5f3a-a7b0-46cc-828d-48a3e514cb0f.png)
NEw Error

**Comment by TannerGabriel** [comment]
The play command requires a song as an argument and it does not seem like you provided one. Please check by entering something similar to this and respond with the result.

```
/play SONG_TITLE 
```
