### ISSUE TITLE
playing songs doesnt work

### ISSUE THREAD

**Issue by Tsunami2360** [TannerGabriel/discord-bot#17]
Hey,

I tried this code and when I used the play command (!play <video id>) the bot joins my voice channel and directly leaves it again, because it thinks the video has already ended. 
But its a video of 5min...
Can you please fix this?

Thanks,
Tsunami#6271

**Comment by TannerGabriel** [comment]
I don't think that it is a problem with the repository. Are you sure that you have all the requirements installed correctly?

Also, please update to the newest version of ytdl-core. If you still have this issue after that, please provide more specific information about your deployment.

**Comment by vervoortkobe** [comment]
Oh, I just saw I didn't install FFMPEG correctly.
Thanks for the response!
