### ISSUE TITLE
commande error

### ISSUE THREAD

**Issue by m3kano07** [TannerGabriel/discord-bot#171]
hi sir
i can't see /play or other commandes
https://imgur.com/a/dcmd6c1

**Comment by TannerGabriel** [comment]
Did you use the `!deploy` command?

**Comment by gcalhoun** [comment]
Hi TannerGabriel,

I am actually running into the same issue. I used the `!deploy` command and it responded with "Deployed!". The only command from the bot that shows up when I type "/" is `/volume`.

**Comment by TannerGabriel** [comment]
Ok, thank you for letting me know. I will take a look at the issue.

**Comment by gcalhoun** [comment]
> Hi TannerGabriel,
> 
> I am actually running into the same issue. I used the `!deploy` command and it responded with "Deployed!". The only command from the bot that shows up when I type "/" is `/volume`.

I should have said it in my original comment but all of the commands show up in the cmd prompt after executing index.js so the issue may lie with bot configuration in the developer portal.

**Comment by TannerGabriel** [comment]
@gcalhoun @m3kano07 I tried, but I can currently not reproduce your issue. Please send me your developer portal configuration and setup information (OS, Node version, etc.).

**Comment by gcalhoun** [comment]
OS: Windows 10
Node: 16.15.0 (recently updated)
OAuth2 Configuration:
![gcalhoun - Discord Developer Portal](https://user-images.githubusercontent.com/15791547/167308491-53a17476-b4ce-409c-8e4d-b75fe518549b.png)

Let me know if there is any additional information I can provide.

**Comment by gcalhoun** [comment]
@TannerGabriel The issue seems to have resolved itself for me. I tried running the bot last night and I was able to see all of the commands. Working through a few other errors that may be related to my version of Node.js., but for me this issue is resolved.

**Comment by crwlrrs** [comment]
I suppose I will provide more information here.
So, my issue is not exactly the same as the issue described here, as none of the commands show up after the bot has responded to the `!deploy` message, as opposed to the `/volume` being the only command showing up. 

Also, similarly to gcalhoun's situation, all of the commands show up in the cmd prompt after executing index.js.
