### ISSUE TITLE
/play command returns an error

### ISSUE THREAD

**Issue by crwlrrs** [TannerGabriel/discord-bot#173]
I have followed all the steps, and most commands work perfectly fine. Although, when i do the `/play` command, the bot joins the channel without playing any music, and i get an error in the command prompt.

1. Follow the steps in the README
2. Perform `/play` command followed by any song

I expected this to play the provided song, but got an error

 - OS: Windows 10
 - CPU architecture: x64

 - Nodejs version: 18.1.0
 - YTDL-core version: 4.11.0

This is the error in question:

Error: Error: Cannot find module 'C:\Users\vilme\discord-bot\node_modules\@discordjs\opus\prebuild\node-v108-napi-v3-win32-x64-unknown-unknown\opus.node'
Require stack:
- C:\Users\vilme\discord-bot\node_modules\@discordjs\opus\lib\index.js
- C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\node_modules\prism-media\src\util\loader.js
- C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\node_modules\prism-media\src\opus\Opus.js
- C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\node_modules\prism-media\src\opus\index.js
- C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\node_modules\prism-media\src\index.js
- C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\dist\audio\TransformerGraph.js
- C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\dist\audio\AudioResource.js
- C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\dist\audio\index.js
- C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\dist\index.js
- C:\Users\vilme\discord-bot\node_modules\discord-player\dist\Structures\Queue.js
- C:\Users\vilme\discord-bot\node_modules\discord-player\dist\Player.js
- C:\Users\vilme\discord-bot\node_modules\discord-player\dist\index.js
- C:\Users\vilme\discord-bot\index.js
Error: Cannot find module 'node-opus'
Require stack:
- C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\node_modules\prism-media\src\util\loader.js
- C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\node_modules\prism-media\src\opus\Opus.js
- C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\node_modules\prism-media\src\opus\index.js
- C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\node_modules\prism-media\src\index.js
- C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\dist\audio\TransformerGraph.js
- C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\dist\audio\AudioResource.js
- C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\dist\audio\index.js
- C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\dist\index.js
- C:\Users\vilme\discord-bot\node_modules\discord-player\dist\Structures\Queue.js
- C:\Users\vilme\discord-bot\node_modules\discord-player\dist\Player.js
- C:\Users\vilme\discord-bot\node_modules\discord-player\dist\index.js
- C:\Users\vilme\discord-bot\index.js
Error: Cannot find module 'opusscript'
Require stack:
- C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\node_modules\prism-media\src\util\loader.js
- C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\node_modules\prism-media\src\opus\Opus.js
- C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\node_modules\prism-media\src\opus\index.js
- C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\node_modules\prism-media\src\index.js
- C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\dist\audio\TransformerGraph.js
- C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\dist\audio\AudioResource.js
- C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\dist\audio\index.js
- C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\dist\index.js
- C:\Users\vilme\discord-bot\node_modules\discord-player\dist\Structures\Queue.js
- C:\Users\vilme\discord-bot\node_modules\discord-player\dist\Player.js
- C:\Users\vilme\discord-bot\node_modules\discord-player\dist\index.js
- C:\Users\vilme\discord-bot\index.js
    at Object.loader [as require] (C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\node_modules\prism-media\src\util\loader.js:12:9)
    at loadOpus (C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\node_modules\prism-media\src\opus\Opus.js:17:17)
    at new OpusStream (C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\node_modules\prism-media\src\opus\Opus.js:46:10)
    at new Encoder (C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\node_modules\prism-media\src\opus\Opus.js:149:5)
    at Object.transformer (C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\dist\audio\TransformerGraph.js:120:24)
    at C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\dist\audio\AudioResource.js:158:60
    at Array.map (<anonymous>)
    at Object.createAudioResource (C:\Users\vilme\discord-bot\node_modules\@discordjs\voice\dist\audio\AudioResource.js:158:41)
    at StreamDispatcher.createStream (C:\Users\vilme\discord-bot\node_modules\discord-player\dist\VoiceInterface\StreamDispatcher.js:108:38)
    at Queue.<anonymous> (C:\Users\vilme\discord-bot\node_modules\discord-player\dist\Structures\Queue.js:663:46)
C:\Users\vilme\discord-bot\node_modules\discord.js\src\rest\RequestHandler.js:350
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Invalid Form Body
content: Must be 2000 or fewer in length.
    at RequestHandler.execute (C:\Users\vilme\discord-bot\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RequestHandler.push (C:\Users\vilme\discord-bot\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async InteractionWebhook.send (C:\Users\vilme\discord-bot\node_modules\discord.js\src\structures\Webhook.js:195:15) {
  method: 'post',
  path: '/webhooks/974059043415011338/aW50ZXJhY3Rpb246OTc0MzQ1OTEzODU2MzIzNjM1OnFCVU40aHNVYkNJSXd3RkdDMGI4V1NsM3Q4aExqQnZnWDlNRkxDY09IQ1A5NWpnZTdDZ25Uc1lNdThldHV1azF4RVkwaG5sanUzUW5sWk1SUEw5OWZpSTZVOTdiU2tqdTV0TWlKcGdBZXpWVWhxakRCa2RGdEUybElFZGdsdTBI?wait=true',
  code: 50035,
  httpStatus: 400,
  requestData: {
    json: {
      content: "There was an error trying to execute that command: Error: Cannot find module 'C:\\Users\\vilme\\discord-bot\\node_modules\\@discordjs\\opus\\prebuild\\node-v108-napi-v3-win32-x64-unknown-unknown\\opus.node'\n" +
        'Require stack:\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\@discordjs\\opus\\lib\\index.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\@discordjs\\voice\\node_modules\\prism-media\\src\\util\\loader.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\@discordjs\\voice\\node_modules\\prism-media\\src\\opus\\Opus.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\@discordjs\\voice\\node_modules\\prism-media\\src\\opus\\index.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\@discordjs\\voice\\node_modules\\prism-media\\src\\index.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\@discordjs\\voice\\dist\\audio\\TransformerGraph.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\@discordjs\\voice\\dist\\audio\\AudioResource.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\@discordjs\\voice\\dist\\audio\\index.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\@discordjs\\voice\\dist\\index.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\discord-player\\dist\\Structures\\Queue.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\discord-player\\dist\\Player.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\discord-player\\dist\\index.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\index.js\n' +
        "Error: Cannot find module 'node-opus'\n" +
        'Require stack:\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\@discordjs\\voice\\node_modules\\prism-media\\src\\util\\loader.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\@discordjs\\voice\\node_modules\\prism-media\\src\\opus\\Opus.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\@discordjs\\voice\\node_modules\\prism-media\\src\\opus\\index.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\@discordjs\\voice\\node_modules\\prism-media\\src\\index.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\@discordjs\\voice\\dist\\audio\\TransformerGraph.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\@discordjs\\voice\\dist\\audio\\AudioResource.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\@discordjs\\voice\\dist\\audio\\index.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\@discordjs\\voice\\dist\\index.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\discord-player\\dist\\Structures\\Queue.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\discord-player\\dist\\Player.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\discord-player\\dist\\index.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\index.js\n' +
        "Error: Cannot find module 'opusscript'\n" +
        'Require stack:\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\@discordjs\\voice\\node_modules\\prism-media\\src\\util\\loader.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\@discordjs\\voice\\node_modules\\prism-media\\src\\opus\\Opus.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\@discordjs\\voice\\node_modules\\prism-media\\src\\opus\\index.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\@discordjs\\voice\\node_modules\\prism-media\\src\\index.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\@discordjs\\voice\\dist\\audio\\TransformerGraph.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\@discordjs\\voice\\dist\\audio\\AudioResource.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\@discordjs\\voice\\dist\\audio\\index.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\@discordjs\\voice\\dist\\index.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\discord-player\\dist\\Structures\\Queue.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\discord-player\\dist\\Player.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\node_modules\\discord-player\\dist\\index.js\n' +
        '- C:\\Users\\vilme\\discord-bot\\index.js',
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined
    },
    files: []
  }
}

**Comment by crwlrrs** [comment]
this got fixed by me reinstalling everything, im saying this if anyone were to experience the same issue

**Comment by gcalhoun** [comment]
I had this error as well. I discovered that my bot was looking for "\node_modules\@discordjs\opus\prebuild\node-**v93**-napi-v3-win32-x64-unknown-unknown\opus.node" when the file path actually was "\node_modules\@discordjs\opus\prebuild\node-**v83**-napi-v3-win32-x64-unknown-unknown\opus.node". I tried look for where that path is determined but in the end I just copied the folder and changed the name to "**v93**".
