### ISSUE TITLE
DisallowedIntents

### ISSUE THREAD

**Issue by duhble** [TannerGabriel/discord-bot#188]
Not sure what this means, yet... but does this have something to do with permissions?

Console Outputs:
/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:250
        throw new Error(unrecoverableErrorCodeMap[error.code]);
              ^

Error [DisallowedIntents]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (/usr/src/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:250:15)
    at async module.exports.login (/usr/src/app/node_modules/discord.js/src/client/Client.js:232:7) {
  code: 'DisallowedIntents'
}

**Comment by DRflamios** [comment]
I have the same things and i tried 'chmod +x' on index.js , WebSocketManager.js and Client.js , but nothings change.

**Comment by TannerGabriel** [comment]
@DRflamios The error talks about the Discord permissions and not your local filesystem permissions. You can change the Discord bot permissions on the [developer portal](https://discord.com/developers/applications/).

**Comment by DRflamios** [comment]
Yeah I realized after posting the comment but I did not think to delete the post.
