### ISSUE TITLE
Error: Cannot find module 'prism-media'

### ISSUE THREAD

**Issue by Addos223** [TannerGabriel/discord-bot#197]
**Describe the bug**
I can't start the discord-bot. It keeps appearing.

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/111061320/201552463-90310cab-e012-48b3-a36e-ef1927d6af10.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 connected through CMD to Ubuntu 22.04
 - Ubuntu CPU: Ampere 2 |Cores

**Dependency versions:**
 - Nodejs version: v16.18.1

**Comment by TannerGabriel** [comment]
Have you installed all the required dependencies including FFMPEG? If not please follow the FFMPEG installation guidelines and see if it works.

**Comment by Addos223** [comment]
Everything is installed, I've updated FFMPEG from 4.43(?) from apt to newest version from git and still nothing.
![image](https://user-images.githubusercontent.com/111061320/201702549-05f2710c-579d-427d-8289-f9e8e3952f81.png)

**Comment by smclean117** [comment]
You could try installing prism-media manually?

npm i prism-media

**Comment by Jmag103** [comment]
Any other way around this? 
![image](https://user-images.githubusercontent.com/100789618/203642934-b500add8-1b7c-49b2-a815-f7e1e11871ab.png)
![image](https://user-images.githubusercontent.com/100789618/203643025-e2da46a0-8f17-4d5b-b672-46e392e79b6a.png)

**Comment by cgwhouse** [comment]
@Jmag103 for better or worse, I am currently getting around this on my local by updating the opus dependency's version spec in `package.json` to `^0.8.0`, which gets it working at least.

**Comment by cgwhouse** [comment]
Note #202
