### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by duclang2403** [TannerGabriel/discord-bot#20]
Error: Cannot find module 'C:\Users\DELL\bot'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:864:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)[39m
[90m    at internal/main/run_main_module.js:18:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

**Comment by TannerGabriel** [comment]
Can you please make sure that you have all the required tools installed. I will also need more information like when you are getting this error and if you have made significant changes to the code.
