### ISSUE TITLE
Bot Won't Play

### ISSUE THREAD

**Issue by Julzies** [TannerGabriel/discord-bot#223]
**Describe the bug**
The bot doesn't find my song if a link is used. When using the search query, the bot finds a song and joins but doesn't play anything.

**To Reproduce**
1. node index.js (VS Code)
2. !deploy
3. /play query:[any link or any search]

**Expected behavior**
To play songs.

**Screenshots (optional)**
I can provide if it becomes necessary

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CPU architecture: x64

**Dependency versions:**
 - Nodejs version: v18.15.0
 - YTDL-core version: 4.11.3

**Additional context (optional)**
There are no error messages so I can't figure out what's wrong. I'm not very good at this but I'm trying to understand :(

**Checklist**:
- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/TannerGabriel/discord-bot/issues?q=is%3Aissue)

**Comment by MintyFreshers** [comment]
I am suffering from this too,
Nodejs: Tried 16 and 18.
OS: Debian 11.

**Comment by MintyFreshers** [comment]
It seems ytdl-core is at fault here. I've downgraded to 4.9.1 (npm i ytdl-core@4.9.1) and it seems to be working fine now.

https://github.com/fent/node-ytdl-core/issues/1201

**Comment by Julzies** [comment]
> It seems ytdl-core is at fault here. I've downgraded to 4.9.1 (npm i ytdl-core@4.9.1) and it seems to be working fine now.
> 
> [fent/node-ytdl-core#1201](https://github.com/fent/node-ytdl-core/issues/1201)

This seems to work
