### ISSUE TITLE
Playing Error

### ISSUE THREAD

**Issue by TlMcook** [TannerGabriel/discord-bot#225]
**Describe the bug**
The Bot will not play music although it will find and queue the track.

**To Reproduce**
1. /play a track
2. wait for Bot to load track
3. bug happens

**Expected behavior**
It is expected to, after the track loads, play the music.

**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/43119444/234736939-20910c46-a1c9-4e1f-8363-7f22d9258a10.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - CPU architecture: x64

**Dependency versions:**
 - Nodejs version: v18.12.1
 - YTDL-core version: v4.11.4

**Comment by Julzies** [comment]
Same issues is happening to me

**Comment by thucngyyen** [comment]
discord-player deprecated 5.x.x, try update to latest and everything change :(

**Comment by TlMcook** [comment]
> npm install ytdl-core@latest
fixes now, thanks.

**Comment by TlMcook** [comment]
Aaand we're back!

**Comment by TlMcook** [comment]
Additionally it seems as though youtube links have stopped working all together.

**Comment by TlMcook** [comment]
This error is originally caused by the YTDL-CORE version being 4.11.4 instead of 4.11.2
