### ISSUE TITLE
Issues with queue?

### ISSUE THREAD

**Issue by jdinhwork** [TannerGabriel/discord-bot#23]
The bot stops playing music after a few songs, but continues adding to queue.

Bug can be recreated by playing multiple songs and skipping through them until the music stops play. Typically the music stops on it’s own, but skipping speeds up the process. If you use the !play function again it says it adds the song to the queue, but doesn’t play anything afterwards.

**Comment by KayPls** [comment]
Have not been able to recreate the bug yet even after inputting over 30 songs.

**Comment by jdinhwork** [comment]
Thanks for replying. I just updated my list of dependencies and it's working now. 👍
