### ISSUE TITLE
Error [TokenInvalid]: An invalid token was provided.

### ISSUE THREAD

**Issue by DylanMCode** [TannerGabriel/discord-bot#239]
**Describe the bug**
After following the instructions on how to setup the bot I am getting an invalid token error.

> C:\Coding Projects\DiscJockey\discord-bot\node_modules\discord.js\src\client\Client.js:214
>     if (!token || typeof token !== 'string') throw new DiscordjsError(ErrorCodes.TokenInvalid);
>                                                    ^
> 
> Error [TokenInvalid]: An invalid token was provided.
>     at module.exports.login (C:\Coding Projects\DiscJockey\discord-bot\node_modules\discord.js\src\client\Client.js:214:52)
>     at Object.<anonymous> (C:\Coding Projects\DiscJockey\discord-bot\index.js:135:8)
>     at Module._compile (node:internal/modules/cjs/loader:1256:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
>     at Module.load (node:internal/modules/cjs/loader:1119:32)
>     at Module._load (node:internal/modules/cjs/loader:960:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
>     at node:internal/main/run_main_module:23:47 {
>   code: 'TokenInvalid'
> }

**To Reproduce**
1.  create discord bot 
2.  clone repo
3.  install dependencies
4.  paste discord bot token into the provided command to create the .env file.
5.  run node index.js

**Screenshot**
![error](https://github.com/TannerGabriel/discord-bot/assets/140769923/a5661168-4df2-45fa-ad3a-91862f8461d4)

**Desktop:**
 - OS: Windows 11

**Dependency versions:**
 - Nodejs version: 18.17.0

**Additional context**
I am able to login to the discord bot with the provided token using my own code from following the official discord.js guide. I have checked to make sure the token is correct in the .env file compared to token in the discord developer website. I have tried to reset my token multiple times and use the updated one and I am still receiving the same error.

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/TannerGabriel/discord-bot/issues?q=is%3Aissue)

**Comment by TannerGabriel** [comment]
When executing the provided command (`echo "DISCORD_TOKEN='INSERT_YOUR_TOKEN_HERE'" > .env
`) in my CLI (zsh) I get:

```
DISCORD_TOKEN='INSERT_YOUR_TOKEN_HERE'
```

You have an extra double quote which is probably the case since you use another terminal.

```
"DISCORD_TOKEN='INSERT_YOUR_TOKEN_HERE'"
```

Removing the double quotes should fix the issue. If you tell me the terminal you are using I can double-check and add a note to the documentation if needed.

**Comment by DylanMCode** [comment]
> When executing the provided command (`echo "DISCORD_TOKEN='INSERT_YOUR_TOKEN_HERE'" > .env `) in my CLI (zsh) I get:
> 
> ```
> DISCORD_TOKEN='INSERT_YOUR_TOKEN_HERE'
> ```
> 
> You have an extra double quote which is probably the case since you use another terminal.
> 
> ```
> "DISCORD_TOKEN='INSERT_YOUR_TOKEN_HERE'"
> ```
> 
> Removing the double quotes should fix the issue. ~If you tell me the terminal you are using I can double-check and add a note to the documentation if needed.~ (Just saw it in the picture).

I just modified the env file and everything works fine now!
