### ISSUE TITLE
Bot connects, loads track, adds it to queue, says its playing the song and then queue finished instantly. No music is played. 

### ISSUE THREAD

**Issue by cschratz** [TannerGabriel/discord-bot#243]
**Describe the bug**

**To Reproduce**
1. Pull latest build from repo
2.  Setup bot to be deployed on Heroku
3.  Run deployment and have bot online and responding to commands.
4. Using the play command add any media type (Youtube, Spotify, etc.) 
5. Bot will connect and say the following: 

⏱ | Loading your track...
🎶 | Song Post Malone - Saint-Tropez (Audio) added to the queue!
▶ | Started playing: Post Malone - Saint-Tropez (Audio)!
✅ | Queue finished!

This all happens instantly the bot does not play the song that was supposedly queued and thinks its finished playing the song immediately. 

**Expected behavior**
I expect the bot to queue the song and play the track as normal before finishing the queue.

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - CPU architecture: [e.g. x64]

**Dependency versions:**
 - Nodejs version: [e.g. 16]
 - YTDL-core version: [e.g. 4.9.1]

**Additional context (optional)**

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/TannerGabriel/discord-bot/issues?q=is%3Aissue)

**Comment by TannerGabriel** [comment]
The `index.js` file features some [debug functionality](https://github.com/TannerGabriel/discord-bot/blob/master/index.js#L71-L83). Please enable it by removing the comments and see if you get any errors. Could you also see if it works when you deploy the bot on your local machine instead of Heroku?

**Comment by TannerGabriel** [comment]
Most likely related to [this issue](https://github.com/Androz2091/discord-player/issues/1761) from the `discord-player` library.
