### ISSUE TITLE
Volume gets down every time the bot disconnects

### ISSUE THREAD

**Issue by elboletaire** [TannerGabriel/discord-bot#263]
**Describe the bug**
Bot volume is too low. And it makes sense considering it's forced to 10 in the `execute` function: https://github.com/TannerGabriel/discord-bot/blob/c3cf341743e55de68e8e849f4b61f0e362f44943/commands/play.js#L43

**To Reproduce**
1. Play some song
2. Set the volume to 100 via `/volume 100`
3. Disconnect the bot
4. Play a new song, you'll notice the volume is down again

**Expected behavior**
To store the volume defined via `/volume`, so consecutive plays have the same volume configured. This should store a `volume` setting to the `settings.json` file, which would allow also to define the volume in the first boot via the settings file.

**Desktop (please complete the following information):**
 - OS: doesn't matter
 - CPU architecture: doesn't matter

**Dependency versions:**
 - Nodejs version: doesn't matter
 - YTDL-core version: doesn't matter

**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/TannerGabriel/discord-bot/issues?q=is%3Aissue)

**Comment by elboletaire** [comment]
BTW I said `disconnect the bot`, because since some time ago the bot just stays in the channel until everyone leaves. So you may need to manually disconnect it from the voice channel to properly try it.

**Comment by TannerGabriel** [comment]
Thank you for letting me know. You can open a PR if you want, or I can take a look.

**Comment by TannerGabriel** [comment]
@elboletaire I opened a PR for this. Can you please test if it works and get back to me?

**Comment by elboletaire** [comment]
> @elboletaire I opened a PR for this. Can you please test if it works and get back to me?

I answered you there.
