### ISSUE TITLE
INVALID_TOKEN error

### ISSUE THREAD

**Issue by BlaNKtext** [TannerGabriel/discord-bot#28]
**Describe the bug**
Its giving a "INVALID_TOKEN" error

**To Reproduce**
1. Go to 'CMD prompt, (i installed dependencies), do "node index.js", let it run, (YES i did put a valid token, i even regenerated it twice.)'

**Expected behavior**
Start the bot

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [.Windows]
 - Browser [Opera GX]

**Additional context**
ive checked it over multiple times i even wrote it down it IS the right token

**Comment by BlaNKtext** [comment]
this is the full error
(node:8584) UnhandledPromiseRejectionWarning: Error [TOKEN_INVALID]: An invalid token was provided.
    at module.exports.login (C:\Users\itsye\discord-bot\node_modules\discord.js\src\client\Client.js:203:52)
    at Object.<anonymous> (C:\Users\itsye\discord-bot\index.js:54:8)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
(node:8584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8584) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by TannerGabriel** [comment]
I can only reproduce your error when inserting an invalid token. Are you sure that you have copied the token instead of another variable as the client secret? If you are not sure, you can use my [discord bot](https://gabrieltanner.org/blog/dicord-music-bot) article as a reference.

If you still get the same error, let me know, and I will try to help as good as I can.

**Comment by axelra82** [comment]
For anyone else wondering in here with similar issues... This happened to me too. Checked the copied token, it was wonky. Simply regenerate it  and make sure it follows the correct JWT forrmat, `xxxxxx.xxxxxx.xxxxxx`👍

**NOTE!** The format is only an example, it should be `random string (dot) random string (dot) random string`
