### ISSUE TITLE
The song is added to the list but no sound plays

### ISSUE THREAD

**Issue by MarcosZeni** [TannerGabriel/discord-bot#287]
**Describe the bug**

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS:win server 201x
 - CPU architecture: [e.g. x86]

**Dependency versions:**
 - Nodejs version: Node.js v18.17.0
 - YTDL-core version:     "ytdl-core": "^4.11.5"

**Additional context (optional)**

**Checklist**:

- [] I included all information required in the sections above
- [] I made sure there are no duplicates of this report [(Use Search)](https://github.com/TannerGabriel/discord-bot/issues?q=is%3Aissue)

**Comment by twlite** [comment]
Please use this extractor instead of internal/default youtube extractor https://github.com/retrouser955/discord-player-youtubei/

**Comment by TannerGabriel** [comment]
Sorry for the late response. I just switched to a different version of `ytdl-core`, which fixes the issue on my end. Let me know if it also works for you.
