### ISSUE TITLE
invalid url : undefined

### ISSUE THREAD

**Issue by Hentomm** [TannerGabriel/discord-bot#29]
**Describe the bug**
invalid url : undefined

**To Reproduce**
1. in discord did !play (video of the song)
2. See error

**Expected behavior**
start to play the song in voice chat

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [windows]

**Additional context**
i haven't changed any of the code in the area it says
i also have Node, NPM, FFMPEG installed

**Comment by TannerGabriel** [comment]
It seems that the dependencies of the applications weren't up to date. I have updated the now, so you should be fine when pulling the repository again.

```bash
git pull origin master
```

You can also try to update the ytdl-core dependency manually, which might help.

```bash
npm install ytdl-core@latest
```

**Comment by Hentomm** [comment]
Ok thank you
