### ISSUE TITLE
future coding request

### ISSUE THREAD

**Issue by MAFPlus** [TannerGabriel/discord-bot#34]
upon playing a song i get theses errors. can you point me in the direction of the files which these lines are located so that i can change it please?

`info.title` will be removed in a near future release, use `info.videoDetails.title` instead.
`info.video_url` will be removed in a near future release, use `info.videoDetails.video_url` instead.

**Comment by TannerGabriel** [comment]
It seems that the ytdl-core library will deprecate these two parameters. You can change them in the play file by just replacing them with the parameters displayed on the right.

I will also fix this in the repository as soon as possible.

**Comment by MAFPlus** [comment]
I just don't see those two items in the play file.

**Comment by TannerGabriel** [comment]
I just updated them you can see the changes in the commit [here](https://github.com/TannerGabriel/discord-bot/commit/7359e4689c07b0c43b326657a5a62d0cde997416).

**Comment by MAFPlus** [comment]
Thanks!
