### ISSUE TITLE
Cannot read property 'get' of undefined when using play command

### ISSUE THREAD

**Issue by noahjsmyth** [TannerGabriel/discord-bot#36]
![Screenshot from 2020-07-20 16-06-47](https://user-images.githubusercontent.com/38191751/87953528-12ac8e80-caa3-11ea-99a0-548dfc021af6.png)
![Screenshot from 2020-07-20 16-07-27](https://user-images.githubusercontent.com/38191751/87953619-2ce66c80-caa3-11ea-9352-b002527bff65.png)
When I use the play command, it throws the error 'Cannot read property get of undefined. I think this is from when it looks for stuff in the queue?

PS: The bot connects to the voice channel but plays no sounds?

**Comment by TannerGabriel** [comment]
Did you try the solution outlined [here](https://github.com/TannerGabriel/discord-bot/issues/21#issuecomment-608995751)? If not, please try it and tell me if it works.

I will look into the problem and try to reproduce it.

**Comment by noahjsmyth** [comment]
> Did you try the solution outlined [here](https://github.com/TannerGabriel/discord-bot/issues/21#issuecomment-608995751)? If not, please try it and tell me if it works.
> 
> I will look into the problem and try to reproduce it.

Yeah, I tried that but still the same error.

**Comment by TannerGabriel** [comment]
Can you please provide more information like your OS, Nodejs version and the song you are trying to play using the play command.

I currently face difficulties reproducing the problem.

**Comment by noahjsmyth** [comment]
> Can you please provide more information like your OS, Nodejs version and the song you are trying to play using the play command.
> 
> I currently face difficulties reproducing the problem.

I'm using a host running Ubuntu, with the most recent nodejs version and I'm trying to play Never Gonna Give You Up

**Comment by noahjsmyth** [comment]
If it's helpful to you, in my index.js I have this:
global.Client = require('./client/Client.js');
global.client = new Discord.Client();

**Comment by TannerGabriel** [comment]
I just tested this again and it worked for me using the following command:

```bash
!play https://www.youtube.com/watch?v=dQw4w9WgXcQ
```

It seems to be working on Nodejs version 12 as well.  Can you try running the application using Docker maybe that will work for you?

It is also hard for me to reproduce issues like yours if you modified my code. Can you please tell me if you are facing the same difficulties when you are using my original code or just with your updated version.

**Comment by noahjsmyth** [comment]
It works with your original code, but the only thing I modified with yours was the index.js file and I added more commands. It seems strange that it's broken now

**Comment by noahjsmyth** [comment]
Ah, I figured it out. I was using `new Discord.Client()` instead of `new Client()`
