### ISSUE TITLE
Plays fine for a minute, then crashes

### ISSUE THREAD

**Issue by tate56** [TannerGabriel/discord-bot#38]
As in the title, !play works and the song goes on for about a minute before the console spits this error and stops 
Error: input stream: Status code: 416
    at ClientRequest.<anonymous> (G:\Git\discord-bot\node_modules\miniget\dist\index.js:157:27)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at TLSSocket.socketOnData (_http_client.js:469:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10)

**Comment by TannerGabriel** [comment]
Can you please provide more information like your OS, Nodejs and dependency versions so it is easier for me to reproduce your issue.

Also did you change something in the codebase or is it the same as in my master branch?

**Comment by tate56** [comment]
No changes to master branch
OS - Windows 10 v19041
Nodejs - v12.18.2
Dependency list - 
music-bot@1.0.0 G:\Git\discord-bot
+-- @discordjs/opus@0.1.0
| +-- node-addon-api@2.0.0
| `-- node-pre-gyp@0.14.0
|   +-- detect-libc@1.0.3
|   +-- mkdirp@0.5.3
|   | `-- minimist@1.2.5
|   +-- needle@2.3.3
|   | +-- debug@3.2.6
|   | | `-- ms@2.1.2
|   | +-- iconv-lite@0.4.24
|   | | `-- safer-buffer@2.1.2
|   | `-- sax@1.2.4 deduped
|   +-- nopt@4.0.3
|   | +-- abbrev@1.1.1
|   | `-- osenv@0.1.5
|   |   +-- os-homedir@1.0.2
|   |   `-- os-tmpdir@1.0.2
|   +-- npm-packlist@1.4.8
|   | +-- ignore-walk@3.0.3
|   | | `-- minimatch@3.0.4
|   | |   `-- brace-expansion@1.1.11
|   | |     +-- balanced-match@1.0.0
|   | |     `-- concat-map@0.0.1
|   | +-- npm-bundled@1.1.1
|   | | `-- npm-normalize-package-bin@1.0.1 deduped
|   | `-- npm-normalize-package-bin@1.0.1
|   +-- npmlog@4.1.2
|   | +-- are-we-there-yet@1.1.5
|   | | +-- delegates@1.0.0
|   | | `-- readable-stream@2.3.7
|   | |   +-- core-util-is@1.0.2
|   | |   +-- inherits@2.0.4 deduped
|   | |   +-- isarray@1.0.0
|   | |   +-- process-nextick-args@2.0.1
|   | |   +-- safe-buffer@5.1.2 deduped
|   | |   +-- string_decoder@1.1.1
|   | |   | `-- safe-buffer@5.1.2 deduped
|   | |   `-- util-deprecate@1.0.2
|   | +-- console-control-strings@1.1.0
|   | +-- gauge@2.7.4
|   | | +-- aproba@1.2.0
|   | | +-- console-control-strings@1.1.0 deduped
|   | | +-- has-unicode@2.0.1
|   | | +-- object-assign@4.1.1
|   | | +-- signal-exit@3.0.2
|   | | +-- string-width@1.0.2
|   | | | +-- code-point-at@1.1.0
|   | | | +-- is-fullwidth-code-point@1.0.0
|   | | | | `-- number-is-nan@1.0.1
|   | | | `-- strip-ansi@3.0.1 deduped
|   | | +-- strip-ansi@3.0.1
|   | | | `-- ansi-regex@2.1.1
|   | | `-- wide-align@1.1.3
|   | |   `-- string-width@1.0.2 deduped
|   | `-- set-blocking@2.0.0
|   +-- rc@1.2.8
|   | +-- deep-extend@0.6.0
|   | +-- ini@1.3.5
|   | +-- minimist@1.2.5 deduped
|   | `-- strip-json-comments@2.0.1
|   +-- rimraf@2.7.1
|   | `-- glob@7.1.6
|   |   +-- fs.realpath@1.0.0
|   |   +-- inflight@1.0.6
|   |   | +-- once@1.4.0 deduped
|   |   | `-- wrappy@1.0.2
|   |   +-- inherits@2.0.4
|   |   +-- minimatch@3.0.4 deduped
|   |   +-- once@1.4.0
|   |   | `-- wrappy@1.0.2 deduped
|   |   `-- path-is-absolute@1.0.1
|   +-- semver@5.7.1
|   `-- tar@4.4.13
|     +-- chownr@1.1.4
|     +-- fs-minipass@1.2.7
|     | `-- minipass@2.9.0 deduped
|     +-- minipass@2.9.0
|     | +-- safe-buffer@5.1.2 deduped
|     | `-- yallist@3.1.1 deduped
|     +-- minizlib@1.3.3
|     | `-- minipass@2.9.0 deduped
|     +-- mkdirp@0.5.3 deduped
|     +-- safe-buffer@5.1.2
|     `-- yallist@3.1.1
+-- discord.js@12.0.2
| +-- @discordjs/collection@0.1.5
| +-- abort-controller@3.0.0
| | `-- event-target-shim@5.0.1
| +-- form-data@3.0.0
| | +-- asynckit@0.4.0
| | +-- combined-stream@1.0.8
| | | `-- delayed-stream@1.0.0
| | `-- mime-types@2.1.26
| |   `-- mime-db@1.43.0
| +-- node-fetch@2.6.0
| +-- prism-media@1.2.1
| +-- setimmediate@1.0.5
| +-- tweetnacl@1.0.3
| `-- ws@7.2.3
+-- ffmpeg@0.0.4
| `-- when@3.7.8
+-- fluent-ffmpeg@2.1.2
| +-- async@3.1.0
| `-- which@1.3.1
|   `-- isexe@2.0.0
`-- ytdl-core@3.1.3
  +-- html-entities@1.3.1
  +-- m3u8stream@0.7.1
  | +-- miniget@1.7.2
  | `-- sax@1.2.4 deduped
  +-- miniget@2.0.1
  `-- sax@1.2.4
