### ISSUE TITLE
Error:TypeError: commandFile.run is not a function

### ISSUE THREAD

**Issue by BotOtaku** [TannerGabriel/discord-bot#39]
**Describe the error**
I put in the chat "t!play https://www.youtube.com/watch?...", this error appears in the console (Error:TypeError: commandFile.run is not a function)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]

**Comment by TannerGabriel** [comment]
Did you change the prefix of the command to `t!` because the standard prefix is `!`. If so are these the only changes you made to the application because I currently cannot reproduce this issue.

**Comment by BotOtaku** [comment]
> Você alterou o prefixo do comando para `t!`porque o prefixo padrão é `!`. Em caso afirmativo, essas são as únicas alterações feitas no aplicativo porque, atualmente, não posso reproduzir esse problema.

Ok man, thanks so much...

**Comment by VideoGameHover** [comment]
Exiting Thread

**Comment by ThomazDaviPlays** [comment]
i'm having the same problem, and this don't helped me so much
