### ISSUE TITLE
Error while running the bot on repl.it

### ISSUE THREAD

**Issue by brigandogaming** [TannerGabriel/discord-bot#41]
 npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2020-08-14T14_15_39_856Z-debug.log
exit status 1
 ^C


**Comment by TannerGabriel** [comment]
The application cannot be started using `npm start` because this command is not configured in the package.json file. So you can either start the application using `node index.js` as stated in the README.md file or add the start command in your package.json and execute it using `npm run start`.

**Comment by brigandogaming** [comment]
![image](https://user-images.githubusercontent.com/69516160/90304859-a70ae500-ded9-11ea-82b0-f58a392f238a.png)
  
Why is this happening now bro?

**Comment by brigandogaming** [comment]
![image](https://user-images.githubusercontent.com/69516160/90305023-70ce6500-dedb-11ea-8c76-b7ad2fec6cc2.png)

Also This

**Comment by TannerGabriel** [comment]
I currently cannot reproduce your issue. Do you get any error messages in the console?

Also, feel free to try the command using other videos and tell me if it works. I personally tried the following:

```
!play https://www.youtube.com/watch?v=dQw4w9WgXcQ
```

**Comment by Oof4** [comment]
maybe its because your hosting it on repl.it, and its not the same. maybe try heroku or something or if that doesn't work, maybe just use the computer to run it for now?

**Comment by Oof4** [comment]
bruh tanner gabirel thats rick roll also thankfully an ad came in my way
