### ISSUE TITLE
Bot Says I Need To Be In A Voice Channel When i Am

### ISSUE THREAD

**Issue by Oof4** [TannerGabriel/discord-bot#44]
the bot says: You need to be in a voice channel to play music!
even when i am. idk why this isnt working, help

**Comment by SugarD-x** [comment]
Make sure the bot has permissions to join that same voice channel, as well as speak in it.

**Comment by Oof4** [comment]
i gave it admin perms but i didnt have ffmpeg on so i think i might close this one
