### ISSUE TITLE
cannot read property get of undefined

### ISSUE THREAD

**Issue by IslandRhythms** [TannerGabriel/discord-bot#45]
`const commando = require("discord.js-commando");
class Skip extends commando.Command {
  constructor(client) {
    super(client, {
      name: "skip",
      group: "music",
      memberName: "skip",
      description: "skips the current song",
    });
  }

  async run(message) {
    const serverQueue = message.client.queue.get(message.guild.id);
    if (!message.member.voice.channel)
      return message.channel.send(
        "You must be in a voice channel to skip songs"
      );
    if (!serverQueue) return message.channel.send("There is nothing to skip");
    serverQueue.connection.dispatcher.end();
  }
}

module.exports = Skip;
`

so I'm adding music functionality to my already existing bot so i'm having it follow the same structure as the other commands. I am getting an error that has to do with the serverQueue variable and am wondering how in your version this doesn't seem to be an issue. The play command follows this structure as well and it works fine but when trying to implement skip for example is when the issues start to come in. Thank you for any assistance.

**Comment by TannerGabriel** [comment]
I will need more information to help you with your problem, like when you are calling the function and with what argument. Also, providing your dependency versions, OS and full error message would be great.

**Comment by IslandRhythms** [comment]
1. OS: Windows 10
2. The error message is sent by the bot and is the title of this post
3. I'm using the most recent version of discord.js as well as the master version of discord.js-commando.
4. I'm not calling skip with any argument, My test has been so far call play with the url to the song on youtube and then call skip after the song has played for a bit. Play works fine but when I call skip the bot sends the error message and the song continues to play.

**Comment by TannerGabriel** [comment]
I'm not quite sure what the error is yet since I have never worked with the discord.js-commando library. It certainly looks like `message.guild.id` is null, and you are therefore getting the error when calling `get()` functions.

Could you validate that you are getting the correct message object in your command by logging it?

**Comment by IslandRhythms** [comment]
thank you for replying but I had managed to figure it out. Just had to move the queue to the index file and import it to the other files. Thank you for taking the time though.
