### ISSUE TITLE
Music ended!

### ISSUE THREAD

**Issue by NaNonnI** [TannerGabriel/discord-bot#5]
When i play a music "!play iXp9xuNi0mU" the bot connect and directly disconnect,
and say "Music ended!"
help

**Comment by TannerGabriel** [comment]
Thank you for the feedback @NaNonnI,

I just looked over your error message and found the solution. The ytdl dependency had a deprecated version which wasn't functioning anymore. I updated it now which fixed it in my case. 

Just test it if you get the time and tell me if it works for you as well. If you have any other questions feel free to ask them and have fun playing around with this repository.

**Comment by PoProstuMieciek** [comment]
I have the same error with your code
