### ISSUE TITLE
It saying that the bot's token is invalid even tho i took it from discord portal

### ISSUE THREAD

**Issue by Azhan131** [TannerGabriel/discord-bot#53]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by SwampDolphin97** [comment]
Is it under bot tag? 
I think you're putting a wrong token. 

**Example**
![image](https://user-images.githubusercontent.com/27912312/101182228-d2c1fe80-3673-11eb-9955-8621b92d1946.png)

**Comment by Azhan131** [comment]
its weird.... i clicked copy
then i paste

**Comment by SwampDolphin97** [comment]
Please close this issue once it starts working. 
@Azhan131

**Comment by Azhan131** [comment]
Ok, I will.

**Comment by SwampDolphin97** [comment]
Please close this issue @TannerGabriel
