### ISSUE TITLE
Invalid permissions flag

### ISSUE THREAD

**Issue by sludgepudge** [TannerGabriel/discord-bot#56]
In ban.js you’re referring to a permissions flag that doesn’t exist (MANAGE_MEMBERS). For banning, the correct flag would be (BAN_MEMBERS) and for kicking it would be (KICK_MEMBERS).

**Comment by TannerGabriel** [comment]
You are right. It seems that I have forgotten to change the permission flags in the commands.

Thank you for letting me know I will quickly fix them.
