### ISSUE TITLE
TypeError: Cannot read property 'execute' of undefined

### ISSUE THREAD

**Issue by DevKilioZOfficiel** [TannerGabriel/discord-bot#6]
Hey,
I have a problem. I install the bot, and i have this error. I have this error when I place an command.

![image](https://user-images.githubusercontent.com/17769612/68534784-c36d6600-0338-11ea-8cb9-fd7b0e09ccf2.png)

**Comment by TannerGabriel** [comment]
It seems like you try to execute a command that doesn't exist in your case ,,!execute". This command is not part of my repository and I think you want to use the !play command instead which is the actual command for playing music (execute is just a function in the command definition).

Hope this helped you. If not just continue asking but please provide more details like minimal reproduction steps.

**Comment by DevKilioZOfficiel** [comment]
Hi, I can test all the available commands. I still have that error with the bot message.

**Comment by TannerGabriel** [comment]
I personally don't get the error when using the repository and can thereby not help you if you don't send me more information about the issue and the minimal reproduction steps.

**Comment by ConnorBaxter** [comment]
I'm had the same issue and fixed it by setting the prefix back to default ('!'). I'm now getting a different error but I will attempt to fix it before reporting it as it could just be my installation.

**Comment by TannerGabriel** [comment]
I'm very sorry that it took me so long to reproduce this issue but I finally managed to and fixed it by updating the ytdl-core version to the latest. I will also add better error logging to prevent errors like this in the future.
