### ISSUE TITLE
error "queue not defined"

### ISSUE THREAD

**Issue by Nils040606** [TannerGabriel/discord-bot#65]
**Describe the bug**
I get an error at the code, that queue is not defined

**To Reproduce**
I just copied the code and the error was there 

**Expected behavior**
The shouldn't be any errors

**Screenshots (optional)**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CPU I dont know what that means but its new and modern

**Dependency versions:**
 - Nodejs version: [e.g. newest]
 - YTDL-core version: [e.g. newest]

**Additional context (optional)**
no one reported this problem, Im using glitch as coding and hosting software

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/TannerGabriel/discord-bot/issues?q=is%3Aissue)

**Comment by TannerGabriel** [comment]
I currently cannot reproduce this issue. This often has to do with your dependency version or the fact that you don't have FFMPEG installed. Follow the common error section in the README or search for [similar issues](https://github.com/TannerGabriel/discord-bot/issues?q=is%3Aissue+is%3Aclosed+queue).

If this does not fix your issue, let me know.
