### ISSUE TITLE
Stage channel

### ISSUE THREAD

**Issue by arturious** [TannerGabriel/discord-bot#73]
![image](https://user-images.githubusercontent.com/81509503/124468470-cfc1f480-dda1-11eb-9d18-a1c02503ed23.png)

can you make it so that the bot can connect to the stage channels?

**Comment by TannerGabriel** [comment]
@arxc This seems to be new in Discord and therefore is not implemented here yet. Thank you for notifying me. I will update it in the next couple of days.

**Comment by TannerGabriel** [comment]
I just look at how to implement this and it seems that the stage channel functionality is not available in discord.js yet. It seems like this will be added in Release Version 13 and I will therefore implement it after this version is released. Here is the [PR](https://github.com/discordjs/discord.js/pull/5456) if you are interested.
