### ISSUE TITLE
Error: FFMPEG not found

### ISSUE THREAD

**Issue by Jbg123s** [TannerGabriel/discord-bot#8]
**Describe the bug**
When I use the !play cmd it gives the error Error: FFMPEG not found But I did install the FFMPEG package.

**To Reproduce**

**Expected behavior**
A I expected the bot to play the song

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [firefox]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Jbg123s** [comment]
![Screenshot_93](https://user-images.githubusercontent.com/58844493/70850586-55aedf80-1e8c-11ea-8637-fd3e6392fce1.png)

**Comment by TannerGabriel** [comment]
You say that you downloaded the ffmpeg package that is included in the package.json file but that is only a tool to use ffmpeg in your application and you still need a local installation of the actual ffmpeg software on the machine the bot should run on. 

Since you are on windows you can either download the software from the [official website](https://www.ffmpeg.org/) or add the [ffmpeg-binaries](https://www.npmjs.com/package/ffmpeg-binaries) package to your package.json (I would suggest taking the first approach because the ffmpeg-binaries is deprecated).

Try this solution and tell me if it helped.

**Comment by Jbg123s** [comment]
I'm hosting my bot on a website why should I need to download ffmpeg on my pc?

**Comment by Jbg123s** [comment]
Sorry for messaging again, but did u get my previous message?

**Comment by TannerGabriel** [comment]
Yeah, the bot still needs to run on some kind of physical machine and this machine needs to have the FFmpeg software installed so it can play music. 
What exactly do you mean by hosting your bot on a website? Do you mean hosting on a server or website that distributes bots for people to use?

Hopefully, this helps you resolve your problem if not please send me more information about what exactly you are using the bot for.

**Comment by Jbg123s** [comment]
I'm hosting my discord bot in a website like github.com.

**Comment by Jbg123s** [comment]
@TannerGabriel

**Comment by TannerGabriel** [comment]
I need your concrete deployment configuration to help you with this issue (A website like Github isn't enough I need concrete information). Nonetheless, your bot will need to be hosted on a physical machine no matter who hosts it (Github or a local deployment) and that machine needs to have FFmpeg installed (I still think that is the issue).

When you deploy the config on a website I would recommend using the already provided Dockerfile for easy deployment but you can still run the node index.js command if you have no experience with Docker yet. 

Another thing I personally would recommend is testing the bot on your local system so you can make sure that your code is working fine. After that, you can continue tweaking the deployment until you get it working.

**Comment by dissolvdgrl** [comment]
I have the same problem, but running on my local Windows 10 machine and I do have ffmpeg installed, I can run `ffmpeg -version` and get output. Is there anything I am missing here?

**Comment by S-Kara** [comment]
@Jbg123s What worked for me is you download from this site https://ffmpeg.zeranoe.com/builds/
extract the zip
go inside the extracted folder and go into the bin folder
you'll find 3 exes, copy them to your bot folder
use cmd (don't forget to cd it to your bot folder) then put in npm install
my bot worked after that
