### ISSUE TITLE
looping songs

### ISSUE THREAD

**Issue by Baggette** [TannerGabriel/discord-bot#85]
A feature where you do /loop (song) (times)  (leave empty for indefinite looping)

**Comment by Ao1Pointblank** [comment]
and shuffle ^

**Comment by Ao1Pointblank** [comment]
> I can probably find the time to implement it on the weekend. If you want, you could also contribute it yourself instead (Just let me know if that is the case).

Sadly, no. I am throwing myself into the deep end of JS to find a solution to the music bot ban; I really don't know what I'm getting into.

**Comment by Baggette** [comment]
> I can probably find the time to implement it on the weekend. If you want, you could also contribute it yourself instead (Just let me know if that is the case).

I know very VERY little js so I wish I could but sadly no

**Comment by TannerGabriel** [comment]
I just implemented a loop command. Therefore I will close this issue.
