### ISSUE TITLE
Bot stops when goes to next song

### ISSUE THREAD

**Issue by Tioli4** [TannerGabriel/discord-bot#87]
**Describe the bug**
Bot stops when goes to next song in the queue

**To Reproduce**
1. Add a song and listen to it
2. Add another song 
3. Wait for the first song to finish
4. The bug happens 

**Expected behavior**
Change to the next song in the queue
**Screenshots (optional)**
![image](https://user-images.githubusercontent.com/79418316/133308008-93132db4-ddfa-41ae-ba5f-a3501a104e2f.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - CPU architecture: ryzen 2400g

**Dependency versions:**
 - Nodejs version: 16.9.1
 - YTDL-core version: latest

**Checklist**:

- [x] I included all information required in the sections above 
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/TannerGabriel/discord-bot/issues?q=is%3Aissue)

**Comment by TannerGabriel** [comment]
Thank you for reporting this issue. I will take a look at the problem later this week.
