### ISSUE TITLE
Bot does not respond to prefix commands (only Slash commands)

### ISSUE THREAD

**Issue by Ao1Pointblank** [TannerGabriel/discord-bot#88]
**Describe the bug**
The bot does not react to any input from chat except slash commands and the hardcoded !deploy command.
prefix is being typed without any whitespaces or typos. (example: !play, or |play). The prefix in config.json file is not read.

**To Reproduce**
1. Be in voice channel with bot
2. Attempt to run command

**Expected behavior**
Bot should respond with either an error or confirmation message

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.2
 - CPU architecture: x86
 - 
**Dependency versions:**
 - Nodejs version: 16.9.1
 - YTDL-core version: 4.9.1

**Additional context (optional)**
Bot has the "Read Message History" permission added from discord dev portal.

Perhaps I need to add commands manually in "client.on("messageCreate", async (message) => { }" like the !deploy command??

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/TannerGabriel/discord-bot/issues?q=is%3Aissue)

**Comment by TannerGabriel** [comment]
@Ao1Pointblank Yes, that is the current implementation since I thought that everybody would prefer using slash commands instead of commands with normal prefixes. It seems that I was wrong about that and will therefore implement prefix commands again when I find the time.

**Comment by Ao1Pointblank** [comment]
> @Ao1Pointblank Yes, that is the current implementation since I thought that everybody would prefer using slash commands instead of commands with normal prefixes. It seems that I was wrong about that and will therefore implement prefix commands again when I find the time.
 
Oh thank goodness that's what it was, and thank you! 
I've never really gotten used to slash commands, sometimes i even misclick and trigger a command for another bot accidentally. Standard text commands can be copy-pasted faster... It's just what me and the people in my server always have done for whatever reason.
