### ISSUE TITLE
Queue view

### ISSUE THREAD

**Issue by 2lol555** [TannerGabriel/discord-bot#94]
Currently, the bot supports the addition of music to the queue, but no actual way to see what is queued

The addition of a /queue command that lists the first x songs in the queue would solve this issue.

The now-discontinued Rythm bot had this feature implemented well.

**Comment by LoganHeasman200** [comment]
I have implemented this feature and is currently a pull request awaiting approval to be merged. Hope this helps!

**Comment by TannerGabriel** [comment]
This feature is implemented, so I will close the issue.
